export { h } from './h'
export { createRender } from './render'
export { renderSlots } from './helper/renderSlots'
export { createTextVNode } from './vNode'
export { getCurrentInstance } from './component'
export { provide, inject} from './apiInject'
export { nextTick } from './schedule'