export { createApp } from './runtime-core/createApp'
export { h } from './runtime-core/h'
export { renderSlots } from './runtime-core/helper/renderSlots'
export { createTextVNode } from './runtime-core/vNode'
export { getCurrentInstance } from './runtime-core/component'
export { provide, inject} from './runtime-core/apiInject'